openapi: "3.0.0"
info:
  version: 1.0.0
  title: HomeNet
  description: |
    listings of properties for sale
  license:
    name: MIT
servers:
- url: http://localhost:3000
paths:
  /listings:
    get:
      summary: Listings By Location
      operationId: listListings
      tags:
      - listings
      parameters:
      - name: Location
        in: query
        description: filter by listings
        required: false
        schema:
          type: string
        allowReserved: true
      responses:
        '200':
          description: Array of Listings
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: create a listing item
      operationId: create listingi item
      tags:
      - listings
      requestBody:
        description: the listing to create
        required: true
        content:
          application/json:    
            schema:
              $ref: "#/components/schemas/Listing"
      responses:
        '200':
          description: Listing created
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /listings/{ListingId}:
    get:
      summary: Info on specific Listing
      operationId: getListingyId
      parameters: 
      - name: ListingId
        in: path
        description: Listing ID
        required: true
        schema:
          type: string
          format: int64
      tags:
      - listings
      responses:
        '200':
          description: Show one Listing item
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Replace a listing by ID
      operationId: putListing
      tags:
      - listings
      parameters:
      - name: ListingId
        in: path
        description: listing id
        required: true
        schema:
          type: string
          format: int64
      requestBody:
        description: the listing you replaced
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Listing'
      responses:
        '200':
          description: The replaced listing was created
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        '201':
          description: The replaced listing
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"
        '204':
          description: The replaced listing
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"   
                
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete specific listitem
      operationId: delete object
      parameters:
      - name: ListingId
        in: path
        description: listing ID
        required: true
        schema:
          type: string
          format: int64 
      tags:
      - listings
      responses:
        '200':
          description: Delete one object listing item
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/ResponseListing"     
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Listing:
      type: object
      properties:
          Address:
            type: string
          Location:
            type: string
          Author:
            type: string
          Price:
            type: number
          MonthlyFee:
            type: string
          Type:
            type: string
          Coordinate:
            type: object
            properties:
              Longitude:
                type: number
              Latitude:
                type: number  
    ResponseListing:
      allOf:
      - $ref: "#/components/schemas/Listing"
      - properties:
          __v:
            type: integer
            format: uint32
          _id:
            type: string
            format: uuid
    ResponseListings:
      type: array
      items:
        $ref: "#/components/schemas/ResponseListing"
    Error:
      required:
        - error
      properties:
        error:
          type: object
          properties:
            expose:
              type: boolean
            statusCode:
              type: integer
              format: uint32
            status:
              type: integer
              format: uint32
            body:
              title: body as escaped json
              type: string
            type:
              title: fault desciption
              type: string
